#name: Build & Test
#
#on:
#  # Run on every commit in a PR, in any branch
#  pull_request:
#    branches:
#
#  # Run when a commit has been made on the primary branches, which should be after a PR
#  push:
#    branches: [ "develop", "main", "master" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@v3
#
#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Configure JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 14
#
#      - name: Set up keystore
#        run: |
#          echo "${{ secrets.KEYSTORE_BASE_64 }}" | base64 --decode >> ./keystore.jks
#          rm -rf local.properties
#          echo "takDebugKeyFile=keystore.jks" >> local.properties
#          echo "takDebugKeyFilePassword=${{ secrets.KEYSTORE_FILE_PASSWORD }}" >> local.properties
#          echo "takDebugKeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> local.properties
#          echo "takDebugKeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> local.properties
#          echo "takReleaseKeyFile=keystore.jks" >> local.properties
#          echo "takReleaseKeyFilePassword=${{ secrets.KEYSTORE_FILE_PASSWORD }}" >> local.properties
#          echo "takReleaseKeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> local.properties
#          echo "takReleaseKeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> local.properties
#
#      - name: Enable Gradle Execution
#        run: chmod +x ./gradlew
#
#      - name: Static Analysis
#        run: ./gradlew detekt
#
#      - name: Assemble Debug APK
#        run: ./gradlew assembleCivDebug
#
#      - name: Publish Detekt Report
#        uses: actions/upload-artifact@v3
#        if: always() # always run even if the previous step fails
#        with:
#          name: detekt-report
#          path: '**/build/reports/detekt'
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        if: always() # always run even if the previous step fails
#        with:
#          name: debug-apk
#          path: ./app/build/outputs/apk/civ/debug/*.apk
